def month(n):
    if (n==1): return ('styczeń')
    elif (n==2): return ('luty')
    elif (n==3): return ('marzec')
    elif (n==4): return ('kwiecień')
    elif (n==5): return ('maj')
    elif (n==6): return ('czerwiec')
    elif (n==7): return ('lipiec')
    elif (n==8): return ('sierpień')
    elif (n==9): return ('wrzesień')
    elif (n==10): return ('pażdziernik')
    elif (n==11): return ('listopad')
    elif (n==12): return ('grudzień')
