x= input ('podaj współżędną x: ')
y= input ('podaj współżędną y: ')
x= int(x)
y = int (y)
if (x>0 and y>0): print('punkt leży w pierwszej ćwiartce')
elif (x<0 and y>0): print('punkt leży w czwartej ćwiartce')
elif (x>0 and y<0): print('punkt leży w drugiej ćwiartce')
elif (x<0 and y<0): print('punkt leży w trzeciej ćwiartce')
elif (x==0 and y==0):print ('punkt leży w punkcie 0,0')
elif (x==0):print ('punkt leży na osi OY')
else: print ('punkt leży na osi OX')